### ISSUE TITLE
Problem executing binaries: `extractor_fmt': undefined method `sort_by!'

### ISSUE THREAD

**Issue by lumiratos** [csw/bioruby-maf#114]
Dear contributors

I am working in compression of MAF files and I find out about your work. I tried to use your gem but until now, I was not able to execute the binaries files. The executable keep saying that he can find the method 'sort_by' in 'extractor_fmt' as we can see next:
`lmatos@sapiens:/media/ngs/luis/MAF/multiz28way$ maf_bgzip chrM.maf
/var/lib/gems/1.8/gems/bio-maf-1.0.1/lib/bio/maf/struct.rb:31:in 'extractor_fmt': undefined method 'sort_by!' for #<Array:0x7f322ab3af70> (NoMethodError)
    from /var/lib/gems/1.8/gems/bio-maf-1.0.1/lib/bio/maf/index.rb:29
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'require'
    from /var/lib/gems/1.8/gems/bio-maf-1.0.1/lib/bio/maf.rb:3
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'require'
    from /var/lib/gems/1.8/gems/bio-maf-1.0.1/lib/bio-maf.rb:21
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'require'
    from /var/lib/gems/1.8/gems/bio-maf-1.0.1/bin/maf_bgzip:6
    from /var/lib/gems/1.8/bin/maf_bgzip:19:in 'load'
    from /var/lib/gems/1.8/bin/maf_bgzip:19`

I think that I had installed everything correctly. First I installed the "Kyoto Cabinet" using the installation process described here (https://github.com/csw/bioruby-maf/wiki/Kyoto-Cabinet). I had installed this gem in a server that has Ubuntu 9.04 and Linux version 2.6.28-19-server which is a bit old. Nevertheless, it is not possible right now to update the operating system of the server.

`lmatos@sapiens:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 9.04
Release:    9.04
Codename:   jaunty`

`lmatos@sapiens:~$ cat /proc/version
Linux version 2.6.28-19-server (buildd@allspice) (gcc version 4.3.3 (Ubuntu 4.3.3-5ubuntu4) ) #66-Ubuntu SMP Sat Oct 16 18:11:06 UTC 2010`

After installing the "Kyoto Cabinet", I was able to install the gem very easily. 
`lmatos@sapiens:~$ sudo gem install bio-maf
Successfully installed bio-maf-1.0.1
1 gem installed`

Can you help me solve my problem dear @csw
Thank you very much for you attention

**Comment by csw** [comment]
Hello @lumiratos, it appears you're using Ruby 1.8; 1.9.3 is the oldest supported version. I haven't tried Ruby 2.0, but I'd definitely suggest installing a more current Ruby version. I found JRuby to offer the best performance, and it might be easier to install if you're dealing with a system Ruby installation.

**Comment by lumiratos** [comment]
Hello again dear @csw 

Thanks very much for the help.I finally could execute maf_bgzip command. I installed the JRuby but it was necessary to install again the gem. It was the first time that I used ruby and gems so I am sorry for the trouble in bother you and thanks again for the help.

Best regards

**Comment by csw** [comment]
Glad I could help!
