### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by lumiratos** [csw/bioruby-maf#116]
Hello dear @csw 

I am using your bioruby-maf plugin for a while now I encounter a problem with the "chr3.maf.gz" file from the UCSC Genome Database. I had downloaded the file "chr3.maf.gz" last September 2013 (https://filesender.fccn.pt/filesender/?vid=56c965a4-9e50-4529-a3eb-00006c9f5e29). It appears that when using your "maf_bgzip" tool a fatal error has detected by the JRE as you can see in the following two files:

Log file: https://dl.dropboxusercontent.com/u/1944285/chr3.maf.old.log
Error report file: https://dl.dropboxusercontent.com/u/1944285/hs_err_pid8984.log

It seems that the UCSC Genome Group sometimes update their data sets. If you download the same file now (http://hgdownload-test.cse.ucsc.edu/goldenPath/hg19/multiz100way/maf/chr3.maf.gz) your tool does not generate any fatal error by the JRE because the file is different. I do not know what is the problem but I also have a compression tool for MAF file and no error occurred for both version of file "chr3.maf.gz".

You also said in a previous issue to contact you directly but I sent you an email on March 20, 2014 and until now you did not get any response. I used the email that is in the following page: https://mcommunity.umich.edu/#profile:cswh
Here in gihub your email is not public so I needed to search your profile online to find some email address.

Hope that you can help me out with this issue

Best regards.

**Comment by csw** [comment]
Hello @lumiratos, sorry I missed your email! That's an interesting problem; it seems the JVM is crashing in VM code during garbage collection. My initial suspicion would be that the Kyoto Cabinet JNI interface is giving the JVM an invalid pointer or otherwise mismanaging memory. (If so, that's going to be a tricky one to debug.) But it's possible that it's a JVM bug, too, especially as that's a relatively old JVM version. Can you try to reproduce that with a newer one, like 1.7 or 1.8?

**Comment by lumiratos** [comment]
Hello again dear @csw 
I am sorry for only reply to your comment now but I have been busy with work. I going to ignore this small issue and I will use the most recent data set version. I have not the time to install a more recent version of JVM because not only the operating system that is running in the server is to old but also I will not use that data set version anymore so for me there ir no problem of ignoring this small issue. I may close this issue and I am sorry once again to not tell anything until now.
