### ISSUE TITLE
Add JRuby compatibility for Kyoto Cabinet

### ISSUE THREAD

**Issue by csw** [csw/bioruby-maf#17]
Right now, indexed access works with Kyoto Cabinet. However, its Ruby library uses the C extension API and doesn't work with JRuby.

Fortunately, the Java API for Kyoto Cabinet is very similar to the Ruby API. (They are both built on top of the core C++ library, so no surprise there, I suppose.) It should be easy to package this up a bit so KC can be used under JRuby with the same API calls I'm using with the native Ruby API. This should probably go in a separate gem, ultimately.

**Comment by pjotrp** [comment]
Yes, there is a trend for that in bindings against JRuby. Good stuff!

**Comment by csw** [comment]
Currently hitting with some kind of string encoding issue with binary keys; they seem to be returned as Unicode garbage. This can be worked around with the byte[] versions of methods and String.from_java_bytes, but DB#match_prefix seems to be entirely broken.

At the very least, the tests would need to be rewritten a bit to cope with this. Grr.

**Comment by csw** [comment]
Done.
